### ISSUE TITLE
Schneider Lab Conversion Progress

### ISSUE THREAD

**Issue by pauladkisson** [catalystneuro/schneider-lab-to-nwb#1]
# Schneider Lab Conversion Progress

![Progress](https://geps.dev/progress/90)
315/330 hrs

# Pre-Conversion

- [x] Repo Setup
- [x] Initial Inspection and Notes: Delineation of *Projects*, *Experiments* and *Data Streams*: [notes](https://docs.google.com/document/d/10GBxtWXjDwt8c_FIBv4eXOYtCXPYFkyeiV4325mNNCU/edit#heading=h.eb2qztkxv4em)
- [x] Identify and request missing data/metadata/READMEs
- [x] Acquire **all** data needed for conversion
 
# Conversion

## Project 1: Behavior + Ephys + Ogen (Grant Zempolich)

- [x] Convert all sessions: #12

### Behavior

- [x] MatBehavior Interface: #3, #7, #8
- [x] Video Interface: #4

### Ephys

- [x] OpenEphys Interface: #2 
- [x] Phy/Kilosort Interface: #2 

### Ogen

- [x] OptogeneticInterface: #9

### Intrinsic Signal Imaging

- [x] IntrinsicSignalImagingInterface: #10 

### Temporal Alignment

- [x] Align ephys, behavior, and video: #19 

### Behavior

- [x] VideoInterface: #26 
- [x] AudioInterface: #26
- [x] SLEAPInterface: #29 

### Stimulus

- [x] Audio Stimulus: #27 
- [x] Visual Stimulus: #30

### Ephys

- [x] WhiteMatter RecordingExtractor: https://github.com/SpikeInterface/spikeinterface/pull/3849
- [x] WhiteMatter RecordingInterface in neuroconv: https://github.com/catalystneuro/neuroconv/pull/1297
- [x] WhiteMatter RecordingInterface: #28 
- [x] Phy/Kilosort Interface: #28

### Temporal Alignment

- [x] Align ephys, behavior, audio, and video: #35

### Data Received

- [x] Raw ephys (OpenEphys binary format)
- [x] Processed behavior (speed, position of the wheel)
- [x] Phy/Kilosort output
- [x] Video
- [x] DLC Live output -> not in the established format 
- [x] Virmen output

### Behavior

- [x] Add processed behavioral data (speed, position of the wheel) #37
- [ ] Adapt BehaviorInterface to VR paradigm 
- [ ] Adapt VideoInterface as necessary
- [ ] DLC Interface (?)

### Ephys  #33

- [x] Adapt OpenEphys Interface as necessary
- [ ] Adapt Phy/Kilosort Interface as necessary

### Temporal Alignment

- [ ] Align ephys, behavior, and video

## Project 4: ndx-sound

- [ ] Community discussion: https://github.com/penalab/ndx-auditory/discussions/1
- [ ] Update ndx-sound: https://github.com/catalystneuro/ndx-sound/pull/11
- [ ] Incorporate updated ndx-sound

# Post-Conversion
- [x] Setup Dandiset(s): [#001259](https://dandiarchive.org/dandiset/001259)
- [ ] Inspection/Validation
- [x] README/Documentation: #15
- [ ] Example Notebooks: https://github.com/dandi/example-notebooks/pull/106, #39
- [x] Streamline dependencies between projects: #34 
- [ ] Final Meeting

# Related Issues

## Neurosift
- [ ] https://github.com/flatironinstitute/neurosift/issues/335
- [ ] https://github.com/flatironinstitute/neurosift/issues/334
